### PR TITLE
Add intro to Flutter Candies.

### PR DESCRIPTION
**Pull request by chenglu**
cc/ @AlexV525 @zmtzawqlp

### CODE REVIEW

**Comment by CaiJingLong** [comment]
The current README of the repositories is generated by [the Github action](https://github.com/fluttercandies/.github-workflow/blob/main/.github/workflows/update-fluttercandies-profile-readme.yml). 

So, I need change the Github workflow file.

**Comment by chenglu** [comment]
Feel free to use these words to the existing workflows, thanks!

**Comment by zmtzawqlp** [comment]
@chenglu thank you for helping improve the description of FlutterCandies , close this pr with https://github.com/fluttercandies/.github/commit/927d54452d283c85f355d0b33812ac68dc38903a

**Comment by chenglu** [comment]
👍

**Pull request closed without merging**
